# Configs

title: Bill Pung
name: Bill Pung
email: pung0013@e.ntu.edu.sg
url: "https://billptw.github.io/"
repository: "billptw/billptw.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
highlighter: rouge
# theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
  
# settings for author profile
author:
  name   : "Bill Pung"
  avatar : "/assets/img/avatar.jpg"
  bio    : "PhD Candidate in AI"
  location: "NTU, Singapore"
  github : billptw
  linkedin: billptw
  twitter: billptw
  email  : pung0013@e.ntu.edu.sg


# # comments by disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "billptw-github-io.disqus.com"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-156335706-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: true
      words_per_minute: 270
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
